export const TOGGLE_THEME = 'TOGGLE_THEME';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const IS_VALID_USER = 'IS_VALID_USER';
export const SHOW_APP_INTRO = 'SHOW_APP_INTRO';

export const GET_TOKEN = 'GET_TOKEN';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';


export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'


export const SET_USER = 'SET_USER'


export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

// need to implement 
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const APPOINTMENT_REQUEST = 'APPOINTMENT_REQUEST'
export const APPOINTMENT_REQUEST_SUCCESS = 'APPOINTMENT_REQUEST_SUCCESS'
export const APPOINTMENT_REQUEST_FAIL = 'APPOINTMENT_REQUEST_FAIL'


export const HOME_Page_APPOINTMENT = 'HOME_Page_APPOINTMENT'

export const ADD_APPOINTMENT_REQUEST = "ADD_APPOINTMENT_REQUEST"
export const ADD_APPOINTMENT_SUCCESS = "ADD_APPOINTMENT_SUCCESS"
export const ADD_APPOINTMENT_FAIL = "ADD_APPOINTMENT_FAIL"


export const APPOINTMENT_count_REQUEST = "APPOINTMENT_count_REQUEST"
export const APPOINTMENT_count_SUCCESS = "APPOINTMENT_count_SUCCESS"
export const APPOINTMENT_count_FAIL = "APPOINTMENT_count_FAIL"

export const GET_SLOT_REQUEST = "GET_SLOT_REQUEST"
export const GET_SLOT_SUCCESS = "GET_SLOT_SUCCESS"
export const GET_SLOT_FAIL = "GET_SLOT_FAIL"


export const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST"
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS"
export const GET_SERVICES_FAIL = "GET_SERVICES_FAIL"



export const GET_CLIENTS_REQUEST = 'GET_CLIENTS_REQUEST'
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'
export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL'

export const GET_STAFF_REQUEST = 'GET_STAFF_REQUEST'
export const GET_STAFF_SUCCESS = 'GET_STAFF_SUCCESS'
export const GET_STAFF_FAIL = 'GET_STAFF_FAIL'

export const GET_UNAVAILABLETY_REQUEST = 'GET_UNAVAILABLETY_REQUEST'
export const GET_UNAVAILABLETY_SUCCESS = 'GET_UNAVAILABLETY_SUCCESS'
export const GET_UNAVAILABLETY_FAIL = 'GET_UNAVAILABLETY_FAIL'

export const RESET_MESSAGE = 'RESET_MESSAGE'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'



